// 2. Data arrays
let legs = ["barbell back squats", "Romanian deadlifts", "Bulgarian split squats", "leg presses", "walking lunges"];
let arms = ["bicep curls", "tricep dips", "hammer curls", "skull crushers", "bench press"];
let chest = ["bench press", "incline dumbbell press", "decline bench press", "push-ups", "chest flyes"];
let core = ["planks", "Russian twists", "bicycle crunches", "leg raises", "mountain climbers"];
// lists generated by AI

// 3. The function with a parameter
function showResult(category) {
    let exercises = "";

    
    if (category === "legs") {
        for (let i = 0; i < chest.length; i++) {
            randomNumber = Math.floor(Math.random() * 5) ;
            exercises += chest[randomNumber] + ", ";
        }
    
       
        
    } else if (category === "arms") {
        for (let i = 0; i < chest.length; i++) {
            randomNumber = Math.floor(Math.random() * 5) ;
            exercises += chest[randomNumber] + ", ";
        }
        
       
        
    } else if (category === "chest") {
        for (let i = 0; i < chest.length; i++) {
            randomNumber = Math.floor(Math.random() * 5) ;
            exercises += chest[randomNumber] + ", ";
        }
       
    } else if (category === "core") {
       for (let i = 0; i < chest.length; i++) {
            randomNumber = Math.floor(Math.random() * 5) ;
            exercises += chest[randomNumber] + ", "
       };
    }


    
    document.getElementById("result").textContent = "Your set is: " + exercises;
}

// 4. The Event Listener with a wrapper
document.getElementById("exercisesBtn").addEventListener("click", () => {
  
    let selectedRadio = document.querySelector("input[type='radio']:checked");
    
    if (selectedRadio) {
        
        showResult(selectedRadio.id);
    } else {
        document.getElementById("result").textContent = "Please select a muscle group first!";
    }
});