// 1. Setup greeting
let rawName = prompt("What is your name?");
let username = rawName.charAt(0).toUpperCase() + rawName.slice(1).toLowerCase();
document.getElementById("greeting").textContent = "Hi there, " + username + "!"; 

// 2. Data arrays
let legs = ["barbell back squats", "Romanian deadlifts", "Bulgarian split squats", "leg presses", "walking lunges"];
let arms = ["bicep curls", "tricep dips", "hammer curls", "skull crushers", "bench press"];
let chest = ["bench press", "incline dumbbell press", "decline bench press", "push-ups", "chest flyes"];
let core = ["planks", "Russian twists", "bicycle crunches", "leg raises", "mountain climbers"];
// lists generated by AI

// 3. The function with a parameter
function showResult(category) {
    let exercises = "";

    // The 'category' parameter tells the function which array to use
    if (category === "legs") {
        randomNumber = Math.floor(Math.random() * 5) ;
        exercises = legs[randomNumber];
    
       
        
    } else if (category === "arms") {
        randomNumber = Math.floor(Math.random() * 5) ;
        exercises = arms[randomNumber];
        
       
        
    } else if (category === "chest") {
        randomNumber = Math.floor(Math.random() * 5) ;
        exercises = chest[randomNumber];
        
      
    
    } else if (category === "core") {
        randomNumber = Math.floor(Math.random() * 5) ;
        exercises = core[randomNumber];
    }


    // Update the UI with the final string
    document.getElementById("result").textContent = "Best exercises are: " + exercises;
}

// 4. The Event Listener with a wrapper
document.getElementById("exercisesBtn").addEventListener("click", () => {
    // Find the currently checked radio button
    let selectedRadio = document.querySelector("input[type='radio']:checked");
    
    if (selectedRadio) {
        // Pass the ID of the radio button (e.g., "legs") as the parameter
        showResult(selectedRadio.id);
    } else {
        document.getElementById("result").textContent = "Please select a muscle group first!";
    }
});