let userName = prompt("What is your name?");
let correctName = userName.charAt(0).toUpperCase() + userName.slice(1).toLowerCase();
document.getElementById("greeting").textContent = "Hi there! " + correctName;


// 2. Data arrays
let legs = ["Barbell back squats", "Romanian deadlifts", "Bulgarian split squats", "Leg presses", "Walking lunges"];
let arms = ["Bicep curls", "Tricep dips", "Hammer curls", "Skull crushers", "Bench press"];
let chest = ["Bench press", "Incline dumbbell press", "Decline bench press", "Push-ups", "Chest flyes"];
let core = ["Planks", "Russian twists", "Bicycle crunches", "Leg raises", "Mountain climbers"];
// lists generated by AI

// 3. The function with a parameter
function showResult(category) {
    let exercises = [];

    if (category === "legs") {
        for (let i = 0; i < legs.length; i++) {
            randomNumber = Math.floor(Math.random() * legs.length) ;
            exercises.push(legs[randomNumber]);
            
        }
        
    } else if (category === "arms") {
        for (let i = 0; i < arms.length; i++) {
            randomNumber = Math.floor(Math.random() * arms.length) ;
            exercises.push(arms[randomNumber]);
        }
        
    } else if (category === "chest") {
        for (let i = 0; i < chest.length; i++) {
            randomNumber = Math.floor(Math.random() * chest.length) ;
            exercises.push(chest[randomNumber]);
        }
       
    } else if (category === "core") {
       for (let i = 0; i < core.length; i++) {
            randomNumber = Math.floor(Math.random() * core.length) ;
            exercises.push(core[randomNumber]);
       };
    }    
    document.getElementById("result").textContent = "Your set is: " + exercises.join(", ");
}

function showSingleResult(category) {
    let exercise = "";

    if (category === "legs") {
        randomNumber = Math.floor(Math.random() * legs.length) ;
        exercise = legs[randomNumber];
        
    } else if (category === "arms") {
        randomNumber = Math.floor(Math.random() * arms.length) ;
        exercise = arms[randomNumber];
        
    } else if (category === "chest") {
        randomNumber = Math.floor(Math.random() * chest.length) ;
        exercise = chest[randomNumber];
       
    } else if (category === "core") {
        randomNumber = Math.floor(Math.random() * core.length) ;
        exercise = core[randomNumber];
    }    
    document.getElementById("result").textContent = "Your exercise is: " + exercise;
}

function addExercise() {
    document.getElementById("newExerciseInput").disabled = false;
    document.getElementById("submitNewExerciseBtn").disabled = false;
}

function submitExercise() {
    let newExercise = document.getElementById("newExerciseInput").value.trim();
    let selectedRadio = document.querySelector("input[type='radio']:checked");
    
    if (newExercise && selectedRadio) {
        if (selectedRadio.id === "legs") {
            legs.push(newExercise);
        } else if (selectedRadio.id === "arms") {
            arms.push(newExercise);
        } else if (selectedRadio.id === "chest") {
            chest.push(newExercise);
        } else if (selectedRadio.id === "core") {
            core.push(newExercise);
        }
        document.getElementById("result").textContent = newExercise + " has been added to the " + selectedRadio.id + " category!";
        document.getElementById("newExerciseInput").value = "";
        document.getElementById("newExerciseInput").disabled = true;
        document.getElementById("submitNewExerciseBtn").disabled = true;
        console.log(legs, arms, chest, core);
    }
}

// 4. The Event Listener with a wrapper
document.getElementById("exercisesBtn").addEventListener("click", () => {
  
    let selectedRadio = document.querySelector("input[type='radio']:checked");
    
    if (selectedRadio) {
        
        showResult(selectedRadio.id);
    } else {
        document.getElementById("result").textContent = "Please select a muscle group first!";
    }
});

document.getElementById("singularExerciseBtn").addEventListener("click", () => {
  
    let selectedRadio = document.querySelector("input[type='radio']:checked");
    
    if (selectedRadio) {
        
        showSingleResult(selectedRadio.id);
    } else {
        document.getElementById("result").textContent = "Please select a muscle group first!";
    }
});

document.getElementById("resetBtn").addEventListener("click", () => {
    document.getElementById("result").textContent = "";
    document.getElementById("legs").checked = true;
    document.getElementById("newExerciseInput").disabled = true;
    document.getElementById("submitNewExerciseBtn").disabled = true;
});

document.getElementById("addExerciseBtn").addEventListener("click", () => {
    addExercise();
});

document.getElementById("submitNewExerciseBtn").addEventListener("click", () => {
    submitExercise();
});
